# Zookeeper config for discovery

spring:
  cloud:
    zookeeper:
      connectString: localhost:2181
    discovery:
      instancePort: ${server.port}
      root: /spring-cloud-service
      preferIpAddress: true
      metadata:
        group: example-admin-group
        version: 1.0